tunnel: 56b70339-745a-4bc8-b72d-86c3c2cc280b
credentials-file: C:\Users\Asus\.cloudflared\56b70339-745a-4bc8-b72d-86c3c2cc280b.json

ingress:
  - hostname: gallerys.my.id
    service: http://localhost:8080
  - service: http_status:404